-- =============================================================================
-- TABLE: LIDSKOE.MD_PRODUCT
-- Compat placeholder for Division 800 (LIDA / LIDSKOE)
-- Source: originally defined in 00_create_external_compat_tables.sql
-- =============================================================================

CREATE TABLE IF NOT EXISTS LIDSKOE.MD_PRODUCT (
    DIVISION VARCHAR(10),
    L1_PRODUCTGROUP VARCHAR(255),
    L2_BRAND VARCHAR(255),
    L3_PACKAGETYPE VARCHAR(255),
    L4_PACKAGESIZE VARCHAR(255),
    L5_UNIQUEITEM VARCHAR(255),
    L6_SKU VARCHAR(255),
    L1_CODE VARCHAR(100),
    L2_CODE VARCHAR(100),
    L3_CODE VARCHAR(100),
    L4_CODE VARCHAR(100),
    L5_CODE VARCHAR(255),
    L6_CODE VARCHAR(100),
    M3STATUS VARCHAR(50),
    VOLUME VARCHAR(100),
    SU_IN_UNIT VARCHAR(100),
    BRAND2 VARCHAR(255),
    BRAND3 VARCHAR(255),
    BRAND2_CODE VARCHAR(100),
    BRAND3_CODE VARCHAR(100),
    ALC_VOL_PERC VARCHAR(100),
    ALCO_NONALCO VARCHAR(100),
    EANCODE VARCHAR(100),
    EAN_KUPACODE VARCHAR(100),
    BUDGETITEM VARCHAR(100),
    INV_ACC_METHOD VARCHAR(100),
    PRODUCEDPURCHASED VARCHAR(100),
    DEPOFEEGROUPCODE VARCHAR(100),
    DEPOFEEGROUPNAME VARCHAR(255),
    EXCISEGROUPCODE VARCHAR(100),
    EXCISEGROUPNAME VARCHAR(255),
    MAINSUPPLIER VARCHAR(255),
    MAINWAREHOUSE VARCHAR(100),
    MAINFILLINGLINE VARCHAR(100),
    MANUFACTURER VARCHAR(255),
    LAUNCHPERIOD VARCHAR(100),
    ENDPERIOD VARCHAR(100),
    LOCALITEMGROUP VARCHAR(255),
    LOCALPRODUCTGROUP VARCHAR(255),
    LOCALLONGNAME VARCHAR(255),
    ATTR1 VARCHAR(255),
    ATTR2 VARCHAR(255),
    ATTR3 VARCHAR(255),
    ATTR4 VARCHAR(255),
    ATTR5 VARCHAR(255),
    LAUNCH_PERIOD VARCHAR(100),
    ENDING_NOTE VARCHAR(255),
    MULTIPACK_CODE VARCHAR(100),
    MULTIPACK VARCHAR(255)
);

-- LIDSKOE.MD_WORKCENTER