CREATE OR REPLACE VIEW ANAPLAN.MD_PRODUCT AS
WITH
CTE_EXCISEGROUPS AS (
    SELECT DODOID AS EXCISEGROUPCODE, DODODE AS EXCISEGROUPNAME
    FROM MVXJDTA.MPDDOC
    WHERE DODOTY = 'VV'
    UNION ALL
    SELECT EXCISEGROUPCODE, EXCISEGROUPNAME
    FROM ref.EXCISE_GROUPS
),
CTE_SALES_CHECK_ITEM AS (
    SELECT ITEMCODE, SUM(VOLUME) AS SALESVOLUME
    FROM ANAPLAN.TD_SALES_SUM_FULL
    WHERE PERIOD BETWEEN
        TO_CHAR(CURRENT_DATE - INTERVAL '24 months', 'YYYY') || '01'
        AND TO_CHAR(CURRENT_DATE, 'YYYYMM')
    GROUP BY ITEMCODE
),
PRODUCT_BASE AS (
    SELECT
        M9FACI AS DIVISION,
        CAST((MM.MMGRP1 || '.' || SG1.SGTX40) AS VARCHAR(108)) AS L1_PRODUCTGROUP,
        CAST(
            CASE MM.MMGRP2
                WHEN '02' THEN 'PRIVATE LABEL'
                WHEN '03' THEN 'SUBCONTRACTING'
                ELSE CASE WHEN HI1.HITX40 IS NULL THEN 'NA' ELSE HI1.HITX40 END
            END AS VARCHAR(108)
        ) AS L2_BRAND,
        CAST(COALESCE(PKG.PACKAGETYPE_LABEL, '99.OTHER') AS VARCHAR(108)) AS L3_PACKAGETYPE,
        CAST(
            CASE WHEN SG5.SGTX40 IS NULL THEN 'NA' ELSE SG5.SGTX40 END
            AS VARCHAR(108)
        ) AS L4_PACKAGESIZE,
        CAST(
            (CASE WHEN HI3.HITX40 IS NULL THEN SG1.SGTX40 || '-NA' ELSE HI3.HITX40 END)
            || ' / ' || COALESCE(PKG.PACKAGETYPE_WORD, 'OTHER')
            || ' / ' || CASE WHEN SG5.SGTX40 IS NULL THEN 'NA' ELSE SG5.SGTX40 END
            AS VARCHAR(108)
        ) AS L5_UNIQUEITEM,
        CAST((MM.MMITDS || ' (' || MM.MMItno || ')') AS VARCHAR(108)) AS L6_SKU,
        CAST(MM.MMGRP1 AS VARCHAR(108)) AS L1_CODE,
        CAST(
            CASE MM.MMGRP2
                WHEN '02' THEN 'PL'
                WHEN '03' THEN 'SUBC'
                ELSE COALESCE(HIE1R.REMAP_VALUE, MM.MMHIE1)
            END AS VARCHAR(108)
        ) AS L2_CODE,
        CAST(
            CASE WHEN MM.MMGRP4 = '43' THEN '99' ELSE COALESCE(PKG.CODE_NORMALIZE, MM.MMGRP4) END
            AS VARCHAR(108)
        ) AS L3_CODE,
        CAST(COALESCE(GRP5R.REMAP_VALUE, MM.MMGRP5) AS VARCHAR(108)) AS L4_CODE,
        CAST(
            (CASE WHEN MM.MMHIE3 = ' ' THEN MM.MMGRP1 || '-999999' ELSE COALESCE(HIE3R.REMAP_VALUE, MM.MMHIE3) END)
            || '-' || COALESCE(PKG.CODE_NORMALIZE, MM.MMGRP4)
            || '-' || COALESCE(GRP5R.REMAP_VALUE, MM.MMGRP5)
            AS VARCHAR(108)
        ) AS L5_CODE,
        CAST(MM.MMITNO AS VARCHAR(108)) AS L6_CODE,
        CAST(MM.MMSTAT AS VARCHAR(108)) AS M3STATUS,
        CAST(MM.MMVOL3 AS VARCHAR(108)) AS VOLUME,
        CAST(
            CASE
                WHEN MM.MMUNMS = 'PC' THEN 1
                WHEN MM.MMGRP4 = '33' AND MM.MMGRP5 = '82' THEN 1
                ELSE MM.MMCFI2
            END AS VARCHAR(108)
        ) AS SU_IN_UNIT,
        CAST(
            CASE HI2.HITX40
                WHEN ' ' THEN 'NA'
                WHEN NULL THEN 'NA'
                ELSE HI2.HITX40
            END AS VARCHAR(108)
        ) AS BRAND2,
        CAST(
            CASE HI3.HITX40
                WHEN ' ' THEN 'NA'
                WHEN NULL THEN 'NA'
                ELSE HI3.HITX40
            END AS VARCHAR(108)
        ) AS BRAND3,
        CAST(COALESCE(HIE2R.REMAP_VALUE, MM.MMHIE2) AS VARCHAR(108)) AS BRAND2_CODE,
        CAST(
            CASE WHEN MM.MMHIE3 = ' ' THEN '999999' ELSE COALESCE(HIE3R.REMAP_VALUE, MM.MMHIE3) END
            AS VARCHAR(108)
        ) AS BRAND3_CODE,
        CAST(
            CASE WHEN TAR.QSITNO IS NOT NULL THEN TAR.QSEVTG::TEXT
                 ELSE ANAPLAN.TO_NUMBER_SPEC(MM.MMCFI1)::TEXT
            END AS VARCHAR(108)
        ) AS ALC_VOL_PERC,
        CASE WHEN ANAPLAN.TO_NUMBER_SPEC(MM.MMCFI1) > 0.5 THEN 'ALCO' ELSE 'NONALCO' END AS ALCO_NONALCO,
        CAST(
            CASE
                WHEN MP1.MPPOPN IS NOT NULL THEN MP1.MPPOPN
                ELSE CASE WHEN MP1.MPPOPN IS NULL THEN 'NA' ELSE MP1.MPPOPN END
            END AS VARCHAR(108)
        ) AS EANCODE,
        CAST(
            CASE WHEN MP1.MPPOPN IS NULL THEN 'NA' ELSE MP1.MPPOPN END
            AS VARCHAR(108)
        ) AS EAN_KUPACODE,
        CAST(
            CASE WHEN GRTI.MMITNO IS NULL THEN MM.MMITNO ELSE MM.MMGRTI END
            AS VARCHAR(108)
        ) AS BUDGETITEM,
        CAST(
            CASE M9VAMT::TEXT
                WHEN '0' THEN '0-zero cost'
                WHEN '1' THEN '1-standard cost'
                WHEN '2' THEN '2-average cost'
                WHEN '3' THEN '3-dynamic cost'
                ELSE '99-other'
            END AS VARCHAR(108)
        ) AS INV_ACC_METHOD,
        CAST(
            CASE WHEN MM.MMMABU = '2' THEN 'Purchased' ELSE 'Produced' END
            AS VARCHAR(108)
        ) AS PRODUCEDPURCHASED,
        CAST(
            CASE MM.MMPDLN
                WHEN '700' THEN CASE WHEN MM.MMCFI4 IS NULL OR MM.MMCFI4 = ' ' THEN '99999' ELSE MM.MMCFI4 END
                WHEN '200' THEN CASE WHEN MM.MMCFI5 IS NULL OR MM.MMCFI5 = ' ' OR MM.MMCFI3 IS NULL OR MM.MMCFI3 = ' ' THEN '99999' ELSE MM.MMGRP4 || '-' || MM.MMCFI5 || '-' || MM.MMCFI3 END
                WHEN '100' THEN CASE WHEN MM.MMCFI3 IS NULL OR MM.MMCFI3 = ' ' OR MM.MMCFI3 = 'eip' THEN '99999' ELSE MM.MMCFI3 END
                WHEN '300' THEN CASE WHEN MM.MMCFI3 IS NULL OR MM.MMCFI3 = ' ' OR MM.MMCFI3 = 'eip' THEN '99999' ELSE MM.MMCFI3 END
                WHEN '400' THEN CASE WHEN MM.MMCFI3 IS NULL OR MM.MMCFI3 = ' ' THEN '99999' ELSE MM.MMCFI3 || '-' || MM.MMGRP4 || '-' || MM.MMGRP5 END
                ELSE CASE WHEN M9FACI IN ('600','606','616') THEN
                          CASE WHEN MM.MMCFI5 IS NULL OR MM.MMCFI5 = ' ' THEN '99999'
                               ELSE SG4.SGTX40 || '-' || CFI5.CTTX15 || '-' || SG5.SGTX40 END
                     ELSE 'undefined' END
            END AS VARCHAR(108)
        ) AS DEPOFEEGROUPCODE,
        CAST(
            CASE MM.MMPDLN
                WHEN '700' THEN CASE WHEN MM.MMCFI4 IS NULL OR MM.MMCFI4 = ' ' THEN 'No deposit fee' ELSE CFI4.CTTX40 END
                WHEN '200' THEN CASE WHEN MM.MMCFI5 IS NULL OR MM.MMCFI5 = ' ' OR MM.MMCFI3 IS NULL OR MM.MMCFI3 = ' ' THEN 'No deposit fee' ELSE SG4.SGTX40 || '-' || CFI5.CTTX15 || '-' || CFI3.CTTX40 END
                WHEN '100' THEN CASE WHEN MM.MMCFI3 IS NULL OR MM.MMCFI3 = ' ' OR MM.MMCFI3 = 'eip' THEN 'No deposit fee' ELSE CFI3.CTTX40 END
                WHEN '300' THEN CASE WHEN MM.MMCFI3 IS NULL OR MM.MMCFI3 = ' ' OR MM.MMCFI3 = 'eip' THEN 'No deposit fee' ELSE CFI3.CTTX40 END
                WHEN '400' THEN CASE WHEN MM.MMCFI3 IS NULL OR MM.MMCFI3 = ' ' THEN 'No deposit fee' ELSE CFI3.CTTX40 || '-' || SG4.SGTX40 || '-' || SG5.SGTX40 END
                ELSE CASE WHEN M9FACI IN ('600','606') THEN
                          CASE WHEN MM.MMCFI5 IS NULL OR MM.MMCFI5 = ' ' THEN 'No deposit fee'
                               ELSE SG4.SGTX40 || '-' || CFI5.CTTX15 || '-' || SG5.SGTX40 END
                     ELSE 'undefined' END
            END AS VARCHAR(108)
        ) AS DEPOFEEGROUPNAME,
        CAST(
            CASE MM.MMPDLN
                WHEN '700' THEN
                    CASE WHEN MM.MMATMO = 'ALUS' THEN 'beer'
                         WHEN MM.MMATMO = 'RDZ' AND ANAPLAN.TO_NUMBER_SPEC(MM.MMCFI1) <= 6.0 THEN 'ferm_till6'
                         WHEN MM.MMATMO = 'RDZ' AND ANAPLAN.TO_NUMBER_SPEC(MM.MMCFI1) > 6.0 THEN 'ferm_over6'
                         WHEN MM.MMATMO IN ('WINE','RDZ_STR') THEN 'ferm_over6'
                         WHEN MM.MMATMO = 'P.A.DZ' THEN 'spirit'
                         WHEN MM.MMATMO IN ('STARPP','STARPP_STR','DRINKOT') THEN 'inter'
                         WHEN MM.MMATMO = 'B.A.DZ' THEN 'sugar'
                         WHEN MM.MMATMO = 'WATER' AND MM.MMCFI3 = 'SD' THEN 'sugar'
                         WHEN MM.MMATMO = 'B.A.DZ.C' AND MM.MMCFI3 = 'SDc' THEN 'soft'
                         WHEN MM.MMATMO = 'B.A.DZ.E' AND MM.MMCFI3 = 'SDe' THEN 'soft'
                         ELSE 'no'
                    END
                WHEN '200' THEN
                    CASE WHEN ANAPLAN.TO_NUMBER_SPEC(MM.MMCFI1) <= 1.3 THEN 'no'
                         WHEN MM.MMGRP1 = '01' THEN 'beer'
                         WHEN MM.MMGRP1 IN ('02','03','04','05') AND MM.MMItgr NOT IN ('2120') AND ANAPLAN.TO_NUMBER_SPEC(MM.MMCFI1) <= 6.0 THEN 'ferm_till6'
                         WHEN MM.MMGRP1 IN ('02','03','04','05') AND MM.MMItgr NOT IN ('2120') AND ANAPLAN.TO_NUMBER_SPEC(MM.MMCFI1) > 6.0 THEN 'ferm_over6'
                         WHEN MM.MMItgr IN ('2120') THEN 'spirit'
                         ELSE 'no'
                    END
                WHEN '400' THEN
                    CASE WHEN ANAPLAN.TO_NUMBER_SPEC(MM.MMCFI1) <= 1.2 THEN 'no'
                         WHEN MM.MMGRP1 = '01' AND ANAPLAN.TO_NUMBER_SPEC(MM.MMCFI1) > 2.8 THEN 'beer'
                         WHEN MM.MMGRP1 IN ('02','03','04') AND ANAPLAN.TO_NUMBER_SPEC(MM.MMCFI1) <= 6.0 THEN 'ferm_till6'
                         WHEN MM.MMGRP1 IN ('02','03','04') AND ANAPLAN.TO_NUMBER_SPEC(MM.MMCFI1) > 6.0 THEN 'ferm_over6'
                         WHEN MM.MMGRP1 = '05' THEN 'spirit'
                         ELSE 'no'
                    END
                WHEN '800' THEN
                    CASE WHEN MM.MMItgr = '8140' AND MM.MMEVGR = '1' THEN '800winebased'
                         WHEN MM.MMItgr = '8100' AND MM.MMEVGR = '1' THEN '800beerover7'
                         WHEN MM.MMItgr = '8105' AND MM.MMEVGR = '1' THEN '800beerto7'
                         WHEN MM.MMItgr = '8115' AND MM.MMEVGR = '1' THEN '800cider'
                         WHEN MM.MMItgr = '8150' AND MM.MMEVGR = '1' THEN '800energy'
                         WHEN MM.MMEVGR IN ('0',' ') THEN 'no'
                         ELSE 'no'
                    END
                ELSE
                    CASE
                        WHEN MM.MMPDLN IN ('100','300','310','320') THEN
                            CASE WHEN MM.MMDWNO = ' ' THEN 'no' ELSE MM.MMDWNO END
                        WHEN MM.MMPDLN IN ('600','606','616') OR M9FACI IN ('600','606','616') THEN
                            CASE
                                WHEN MM.MMCFI3 = 'SU2' THEN 'soft'
                                WHEN MM.MMCFI3 = 'SU0' THEN 'no'
                                WHEN MM.MMCFI3 IN ('SU1','SU3','SU4','SU5') THEN 'sugar'
                                WHEN ANAPLAN.TO_NUMBER_SPEC(MM.MMCFI1) <= 1.3 OR MM.MMSPE4 = ' ' THEN 'no'
                                WHEN SUBSTRING(MM.MMSPE4, 1, 3) IN ('110') THEN 'beer'
                                WHEN SUBSTRING(MM.MMSPE4, 1, 3) IN ('280','299') THEN 'spirit'
                                WHEN SUBSTRING(MM.MMSPE4, 1, 3) IN ('210','215') THEN 'ferm_till_8.5'
                                WHEN SUBSTRING(MM.MMSPE4, 1, 3) IN ('230','235') THEN 'ferm_over_8.5'
                                ELSE 'no'
                            END
                        ELSE 'undefined'
                    END
            END AS VARCHAR(108)
        ) AS EXCISEGROUPCODE,
        CAST(
            CASE WHEN MBSUNO IN ('',' ') THEN 'NA' ELSE UPPER(SUP.IDSUNM) || '(' || MBSUNO || ')' END
            AS VARCHAR(108)
        ) AS MAINSUPPLIER,
        CAST(
            CASE WHEN M9REWH = '200' THEN '203 - LC excise warehouse' ELSE M9REWH || ' - ' || MWWHNM END
            AS VARCHAR(108)
        ) AS MAINWAREHOUSE,
        M9WCLN || '-' || PPPLNM AS MAINFILLINGLINE,
        CAST(
            CASE WHEN MM.MMPROD IN ('',' ') THEN 'NA' ELSE UPPER(SUL.IDSUNM) || '(' || MM.MMPROD || ')' END
            AS VARCHAR(108)
        ) AS MANUFACTURER,
        CAST(
            (CASE WHEN MM.MMItRF = ' ' THEN '99' ELSE MM.MMItRF END || ' - ' || 'OTHER')
            AS VARCHAR(108)
        ) AS LAUNCHPERIOD,
        CAST(
            CASE WHEN MBSTTX IN (' ','') THEN 'NA' ELSE MBSTTX END AS VARCHAR(108)
        ) AS ENDPERIOD,
        CAST(
            CASE
                WHEN MM.MMPDLN = '100' THEN MM.MMItGR || ' - ' || ITGR.CTTX40
                WHEN MM.MMGRP1 IN ('01','02','03','04','05','06','07','08','09','10','11','12','13','14')
                     THEN MM.MMGRP1 || '.' || SG1.SGTX40
                ELSE '99.OTHER - ' || MM.MMGRP1
            END AS VARCHAR(108)
        ) AS LOCALITEMGROUP,
        CAST((MM.MMItCL || ' - ' || ITCL.CTTX40) AS VARCHAR(108)) AS LOCALPRODUCTGROUP,
        CAST((MM.MMITNO || ' ' || MM.MMFUDS) AS VARCHAR(108)) AS LOCALLONGNAME,
        CAST(
            CASE
                WHEN MM.MMPDLN = '200' AND MM.MMGRP4 = '31' AND MM.MMEVGR = ' ' THEN 1
                WHEN MM.MMPDLN = '400' AND MM.MMCFI3 IN ('4A','4A0') THEN 1
                WHEN MM.MMPDLN = '600' AND MM.MMCFI5 = 'N' THEN 1
                WHEN MM.MMPDLN = '700' AND MM.MMCFI4 IN ('7BB00','7DK00','7GB00','7ND00','7RD00') THEN 1
                WHEN MM.MMPDLN = '100' AND MM.MMCFI3 = 'EIP' THEN 1
                ELSE 0
            END AS VARCHAR(108)
        ) AS ATTR1,
        CAST(SIT.IFSITE AS VARCHAR(108)) AS ATTR2,
        CAST(NULL AS VARCHAR(108)) AS ATTR3,
        CAST(NULL AS VARCHAR(108)) AS ATTR4,
        CAST(NULL AS VARCHAR(108)) AS ATTR5,
        MM.MMItRF AS LAUNCH_PERIOD,
        MBSTTX AS ENDING_NOTE,
        CASE WHEN MM.MMPDLN IN ('100','400') THEN MM.MMGRP3 ELSE MM.MMGRP5 END AS MULTIPACK_CODE,
        CASE WHEN MM.MMPDLN IN ('100','400') THEN SG3.SGTX40 ELSE SG5.SGTX40 END AS MULTIPACK
    FROM MVXJDTA.MITMAS MM
    LEFT JOIN MVXJDTA.MITMAS GRTI
        ON GRTI.MMCONO = MM.MMCONO
       AND GRTI.MMItNO = MM.MMGRTI
    LEFT JOIN CTE_SALES_CHECK_ITEM SC
        ON MM.MMITNO = SC.ITEMCODE
    LEFT JOIN MVXJDTA.MITSCH SG1
        ON SG1.SGCONO = MM.MMCONO
       AND SG1.SGGLVL = 1
       AND SG1.SGSGP0 = MM.MMGRP1
    LEFT JOIN MVXJDTA.MITSCH SG2
        ON SG2.SGCONO = MM.MMCONO
       AND SG2.SGGLVL = 2
       AND SG2.SGSGP0 = MM.MMGRP2
    LEFT JOIN MVXJDTA.MITSCH SG3
        ON SG3.SGCONO = MM.MMCONO
       AND SG3.SGGLVL = 3
       AND SG3.SGSGP0 = MM.MMGRP3
    LEFT JOIN MVXJDTA.MITSCH SG4
        ON SG4.SGCONO = MM.MMCONO
       AND SG4.SGGLVL = 4
       AND SG4.SGSGP0 = MM.MMGRP4
    LEFT JOIN MVXJDTA.MITSCH SG5
        ON SG5.SGCONO = MM.MMCONO
       AND SG5.SGGLVL = 5
       AND SG5.SGSGP0 = MM.MMGRP5
    LEFT JOIN MVXJDTA.MITHRY HI1
        ON HI1.HICONO = MM.MMCONO
       AND HI1.HIHLVL = 1
       AND HI1.HIHIE0 = MM.MMHIE1
    LEFT JOIN MVXJDTA.MITHRY HI2
        ON HI2.HICONO = MM.MMCONO
       AND HI2.HIHLVL = 2
       AND HI2.HIHIE0 = MM.MMHIE2
    LEFT JOIN MVXJDTA.MITHRY HI3
        ON HI3.HICONO = MM.MMCONO
       AND HI3.HIHLVL = 3
       AND HI3.HIHIE0 = MM.MMHIE3
    LEFT JOIN MVXJDTA.CSYTAB CFI3
        ON CFI3.CTCONO = MM.MMCONO
       AND CFI3.CTSTCO = 'CFI3'
       AND CFI3.CTSTKY = MM.MMCFI3
    LEFT JOIN MVXJDTA.CSYTAB CFI4
        ON CFI4.CTCONO = MM.MMCONO
       AND CFI4.CTSTCO = 'CFI4'
       AND CFI4.CTSTKY = MM.MMCFI4
    LEFT JOIN MVXJDTA.CSYTAB CFI5
        ON CFI5.CTCONO = MM.MMCONO
       AND CFI5.CTSTCO = 'CFI5'
       AND CFI5.CTSTKY = MM.MMCFI5
    LEFT JOIN MVXJDTA.CSYTAB ITGR
        ON ITGR.CTCONO = MM.MMCONO
       AND ITGR.CTSTCO = 'ITGR'
       AND ITGR.CTSTKY = MM.MMITGR
    LEFT JOIN MVXJDTA.CSYTAB ITCL
        ON ITCL.CTCONO = MM.MMCONO
       AND ITCL.CTSTCO = 'ITCL'
       AND ITCL.CTSTKY = MM.MMItCL
    LEFT JOIN MVXJDTA.MITFAC
        ON MM.MMCONO = M9CONO
       AND MM.MMITNO = M9ITNO
       AND M9FACI <> '800'
    LEFT JOIN MVXJDTA.MITBAL
        ON MBCONO = MM.MMCONO
       AND MBITNO = MM.MMITNO
       AND MBWHLO = M9REWH
    LEFT JOIN MVXJDTA.MITWHL
        ON MWCONO = MBCONO
       AND MBWHLO = MWWHLO
    LEFT JOIN MVXJDTA.CIDMAS SUP
        ON SUP.IDCONO = MBCONO
       AND SUP.IDSUNO = MBSUNO
    LEFT JOIN MVXJDTA.CIDMAS SUL
        ON SUL.IDCONO = MM.MMCONO
       AND SUL.IDSUNO = MM.MMPROD
    LEFT JOIN MVXJDTA.MPDWCT PP
        ON MM.MMCONO = PP.PPCONO
       AND M9FACI = PPFACI
       AND M9WCLN = PPPLGR
    LEFT JOIN (
        SELECT MPCONO, MPITNO, MAX(MPPOPN) AS MPPOPN
        FROM MVXJDTA.MITPOP
        WHERE MPALWT = '2'
        GROUP BY MPCONO, MPITNO
    ) MP1
        ON MP1.MPCONO = MM.MMCONO
       AND MP1.MPITNO = MM.MMITNO
    LEFT JOIN (
        SELECT QSITNO, QSEVTG
        FROM (
            SELECT ROW_NUMBER() OVER (
                       PARTITION BY QSITNO
                       ORDER BY QSITNO, QSQTE1 DESC
                   ) AS ORDR,
                   TMP.*
            FROM MVXJDTA.QMSTST TMP
            WHERE QSQTST = 'C265'
              AND SUBSTRING(QSSPEC, 9) = 'MAX ALC'
        ) SUB
        WHERE ORDR = 1
    ) TAR
        ON MM.MMITNO = TAR.QSITNO
    LEFT JOIN (
        SELECT DISTINCT IFITNO, IFSUNO, IFSITE
        FROM MVXJDTA.MITVEN
    ) SIT
        ON SIT.IFITNO = MM.MMITNO
       AND SIT.IFSUNO = MBSUNO
    LEFT JOIN ref.MD_PRODUCT_PACKAGEGROUP PKG
        ON PKG.MMGRP4 = MM.MMGRP4
    LEFT JOIN ref.MD_PRODUCT_HIE1_REMAP HIE1R
        ON HIE1R.MMHIE1 = MM.MMHIE1
    LEFT JOIN ref.MD_PRODUCT_HIE2_REMAP HIE2R
        ON HIE2R.MMHIE2 = MM.MMHIE2
    LEFT JOIN ref.MD_PRODUCT_HIE3_REMAP HIE3R
        ON HIE3R.MMHIE3 = MM.MMHIE3
    LEFT JOIN ref.MD_PRODUCT_MMGRP5_REMAP GRP5R
        ON GRP5R.MMGRP5 = MM.MMGRP5
    WHERE MM.MMCONO = 100
      AND MM.MMITY IN ('10')
      AND MM.MMSTAT >= '10'
      AND SG1.SGTX40 IS NOT NULL
      AND (MM.MMSTAT <= '20' OR SC.ITEMCODE IS NOT NULL)
      AND M9FACI <> '800'
      AND M9FACI IS NOT NULL
)
SELECT
    PR.DIVISION, PR.L1_PRODUCTGROUP, PR.L2_BRAND, PR.L3_PACKAGETYPE, PR.L4_PACKAGESIZE,
    PR.L5_UNIQUEITEM, PR.L6_SKU, PR.L1_CODE, PR.L2_CODE, PR.L3_CODE, PR.L4_CODE,
    PR.L5_CODE, PR.L6_CODE, PR.M3STATUS, PR.VOLUME, PR.SU_IN_UNIT,
    PR.BRAND2, PR.BRAND3, PR.BRAND2_CODE, PR.BRAND3_CODE,
    PR.ALC_VOL_PERC, PR.ALCO_NONALCO, PR.EANCODE, PR.EAN_KUPACODE, PR.BUDGETITEM,
    PR.INV_ACC_METHOD, PR.PRODUCEDPURCHASED, PR.DEPOFEEGROUPCODE, PR.DEPOFEEGROUPNAME,
    PR.EXCISEGROUPCODE,
    CAST(EG.EXCISEGROUPNAME AS VARCHAR(108)) AS EXCISEGROUPNAME,
    PR.MAINSUPPLIER, PR.MAINWAREHOUSE, PR.MAINFILLINGLINE, PR.MANUFACTURER,
    PR.LAUNCHPERIOD, PR.ENDPERIOD, PR.LOCALITEMGROUP, PR.LOCALPRODUCTGROUP,
    PR.LOCALLONGNAME, PR.ATTR1, PR.ATTR2, PR.ATTR3, PR.ATTR4, PR.ATTR5,
    PR.LAUNCH_PERIOD, PR.ENDING_NOTE, PR.MULTIPACK_CODE, PR.MULTIPACK
FROM PRODUCT_BASE PR
LEFT JOIN CTE_EXCISEGROUPS EG
    ON PR.EXCISEGROUPCODE = EG.EXCISEGROUPCODE

UNION ALL

SELECT
    DIVISION, L1_PRODUCTGROUP, L2_BRAND, L3_PACKAGETYPE, L4_PACKAGESIZE,
    L5_UNIQUEITEM, L6_SKU, L1_CODE, L2_CODE, L3_CODE, L4_CODE, L5_CODE, L6_CODE,
    M3STATUS, VOLUME, SU_IN_UNIT, BRAND2, BRAND3, BRAND2_CODE, BRAND3_CODE,
    ALC_VOL_PERC, ALCO_NONALCO, EANCODE, EAN_KUPACODE, BUDGETITEM, INV_ACC_METHOD,
    PRODUCEDPURCHASED, DEPOFEEGROUPCODE, DEPOFEEGROUPNAME, EXCISEGROUPCODE,
    EXCISEGROUPNAME, MAINSUPPLIER, MAINWAREHOUSE, MAINFILLINGLINE, MANUFACTURER,
    LAUNCHPERIOD, ENDPERIOD, LOCALITEMGROUP, LOCALPRODUCTGROUP, LOCALLONGNAME,
    ATTR1, ATTR2, ATTR3, ATTR4, ATTR5, LAUNCH_PERIOD, ENDING_NOTE,
    MULTIPACK_CODE, MULTIPACK
FROM LIDSKOE.MD_PRODUCT
WHERE DIVISION = '800'

UNION ALL

SELECT
    DIVISION, L1_PRODUCTGROUP, L2_BRAND, L3_PACKAGETYPE, L4_PACKAGESIZE,
    L5_UNIQUEITEM, L6_SKU, L1_CODE, L2_CODE, L3_CODE, L4_CODE, L5_CODE, L6_CODE,
    M3STATUS, VOLUME, SU_IN_UNIT, BRAND2, BRAND3, BRAND2_CODE, BRAND3_CODE,
    ALC_VOL_PERC, ALCO_NONALCO, EANCODE, EAN_KUPACODE, BUDGETITEM, INV_ACC_METHOD,
    PRODUCEDPURCHASED, DEPOFEEGROUPCODE, DEPOFEEGROUPNAME, EXCISEGROUPCODE,
    EXCISEGROUPNAME, MAINSUPPLIER, MAINWAREHOUSE, MAINFILLINGLINE, MANUFACTURER,
    LAUNCHPERIOD, ENDPERIOD, LOCALITEMGROUP, LOCALPRODUCTGROUP, LOCALLONGNAME,
    ATTR1, ATTR2, ATTR3, ATTR4, ATTR5, LAUNCH_PERIOD, ENDING_NOTE,
    MULTIPACK_CODE, MULTIPACK
FROM M3SKY.MD_PRODUCT
WHERE DIVISION = '400';

COMMENT ON VIEW ANAPLAN.MD_PRODUCT IS
    'Product master. AD_EXCISEGROUPS + AD_SALES_CHECK_ITEM inlined as CTEs. TO_NUMBER_SPEC. OLVISII.QEAN02_300 and @GM3PRD1 DB links removed (need compat tables if data required).';