CREATE OR REPLACE VIEW ANAPLAN.MD_SEMIPRODUCT AS
WITH SEMIPRODUCT_BASE AS (
    SELECT
        CASE WHEN MM.MMPDLN IN ('310','320') THEN '300' ELSE MM.MMPDLN END AS DIVISION,
        CAST(
            CASE
                WHEN MM.MMGRP1 IN ('01','02','03','04','05','06','07','08','09','10','11','12','13','14')
                    THEN MM.MMGRP1 || '.' || SG1.SGTX40
                ELSE '99.OTHER - ' || MM.MMGRP1
            END AS VARCHAR(108)
        ) AS L1_PRODUCTGROUP,
        CAST(CASE MM.MMGRP1 WHEN ' ' THEN '99' ELSE MM.MMGRP1 END AS VARCHAR(108)) AS L1_CODE,
        CAST((MM.MMITDS || ' (' || MM.MMITNO || ')') AS VARCHAR(108)) AS L6_SKU,
        CAST(MM.MMITNO AS VARCHAR(108)) AS L6_CODE,
        CAST((MM.MMITGR || ' - ' || ITGR.CTTX40) AS VARCHAR(108)) AS LOCALITEMGROUP,
        CAST(CASE WHEN MM.MMMABU = '2' THEN 'Purchased' ELSE 'Produced' END AS VARCHAR(108)) AS PRODUCEDPURCHASED
    FROM MVXJDTA.MITMAS MM
    LEFT JOIN MVXJDTA.CSYTAB ITGR
        ON ITGR.CTCONO = MM.MMCONO
       AND ITGR.CTSTCO = 'ITGR'
       AND ITGR.CTSTKY = MM.MMITGR
    LEFT JOIN MVXJDTA.MITSCH SG1
        ON SG1.SGCONO = MM.MMCONO
       AND SG1.SGGLVL = 1
       AND SG1.SGSGP0 = MM.MMGRP1
    WHERE MM.MMITTY = '40'
      AND MM.MMSALE::TEXT = '1'
      AND MM.MMSTAT <= '20'
)
SELECT *
FROM SEMIPRODUCT_BASE;

COMMENT ON VIEW ANAPLAN.MD_SEMIPRODUCT IS
    'Semi-finished product master. Reads MVXJDTA only. DECODE → CASE.';