CREATE OR REPLACE VIEW ANAPLAN.MD_WORKCENTER AS
WITH WORKCENTER_BASE AS (
    SELECT
        PPFACI                          AS DIVISION,
        PPFACI || '_' || PPPLGR         AS WORKCENTER_CODE,
        PPPLNM                          AS WORKCENTER_NAME,
        PPFACI || '_' || PPCOCE         AS COSTCENTER_CODE,
        COALESCE(WG.WORKCENTER_GROUP, 'OTHER') AS WORKCENTER_GROUP
    FROM MVXJDTA.MPDWCT
    LEFT JOIN ref.WORKCENTER_GROUP WG
        ON WG.PPPLGR = MPDWCT.PPPLGR
    WHERE PPPLTP::TEXT = '1'
      AND PPCINA::TEXT = '1'
      AND PPFACI NOT IN ('800','400')
)
SELECT DIVISION, WORKCENTER_CODE, WORKCENTER_NAME, COSTCENTER_CODE, WORKCENTER_GROUP
FROM WORKCENTER_BASE

UNION ALL

SELECT DIVISION, WORKCENTER_CODE, WORKCENTER_NAME, COSTCENTER_CODE, WORKCENTER_GROUP
FROM LIDSKOE.MD_WORKCENTER
WHERE DIVISION = '800'

UNION ALL

SELECT DIVISION, WORKCENTER_CODE, WORKCENTER_NAME, COSTCENTER_CODE, WORKCENTER_GROUP
FROM M3SKY.MD_WORKCENTER
WHERE DIVISION = '400';

COMMENT ON VIEW ANAPLAN.MD_WORKCENTER IS
    'Work centre master. Large CASE PPPLGR -> ref.WORKCENTER_GROUP JOIN. PPPLTP/PPCINA int casts fixed.';