CREATE OR REPLACE VIEW ANAPLAN.TD_ACTUAL_MO_TIME AS
WITH
    CTE_MWOPTS_MAIN AS (
        SELECT
            DHFACI AS DIVI,
            DHMFNO,
            DHPRNO AS PRODUCT,
            DHANBR,
            DHMAQT,
            DHTRDT AS TRDT,
            DHPLGR AS PRODUCTION_LINE,
            DHUPIT AS MACHINE_TIME,
            DHUMAT AS LABOR_TIME,
            DHUSET AS MACHINE_SETUP_TIME,
            DHUMAS AS LABOR_SETUP_TIME
        FROM MVXJDTA.MWOPTS
        WHERE DHCONO = 100
          AND DHFACI NOT IN ('800','400')
          AND DHTRDT >= 20220101
    ),
    CTE_MWOPTS_800 AS (
        SELECT
            DHFACI AS DIVI,
            DHMFNO,
            DHPRNO AS PRODUCT,
            DHANBR,
            DHMAQT,
            DHTRDT AS TRDT,
            DHPLGR AS PRODUCTION_LINE,
            DHUPIT AS MACHINE_TIME,
            DHUMAT AS LABOR_TIME,
            DHUSET AS MACHINE_SETUP_TIME,
            DHUMAS AS LABOR_SETUP_TIME
        FROM LIDSKOE.MWOPTS
        WHERE DHCONO = 100
          AND DHFACI = '800'
          AND DHTRDT >= 20220101
    ),
    CTE_ACTUAL_MO_SOURCE AS (
        SELECT * FROM CTE_MWOPTS_MAIN
        UNION ALL
        SELECT * FROM CTE_MWOPTS_800
    ),
    CTE_ACTUAL_MO_TIME AS (
        SELECT
            DIVI AS DIVISION,
            DIVI || '_' || PRODUCTION_LINE AS WORKCENTER,
            PRODUCT AS ITEMCODE,
            SUBSTRING(TRDT::TEXT, 1, 6) AS PERIOD,
            SUM(MACHINE_TIME + MACHINE_SETUP_TIME) AS TOTAL_MACHINE_TIME,
            SUM(LABOR_TIME + LABOR_SETUP_TIME) AS TOTAL_LABOR_TIME
        FROM CTE_ACTUAL_MO_SOURCE
        GROUP BY
            DIVI,
            PRODUCTION_LINE,
            PRODUCT,
            SUBSTRING(TRDT::TEXT, 1, 6)
    )
SELECT
    DIVISION,
    WORKCENTER,
    ITEMCODE,
    PERIOD,
    TOTAL_MACHINE_TIME,
    TOTAL_LABOR_TIME
FROM CTE_ACTUAL_MO_TIME

UNION ALL

SELECT
    DIVISION,
    WORKCENTER,
    ITEMCODE,
    PERIOD,
    TOTAL_MACHINE_TIME,
    TOTAL_LABOR_TIME
FROM M3SKY.TD_ACTUAL_MO_TIME;