CREATE OR REPLACE VIEW ANAPLAN.TD_COGS_OPERATIONS AS

WITH CTE_OPERATIONS AS (
    SELECT DISTINCT
        MPDOPE.POFACI                     AS DIVISION,
        MPDOPE.POPRNO                     AS PRODUCT,
        CASE
            WHEN MPDOPE.POFACI = '400' THEN MPDOPE.POPLGR
            ELSE MITFAC.M9WCLN
        END                               AS PRODUCTIONLINE,
        MB1.MBEOQT                         AS ORDERQTY,
        MB1.MBEOQT * MITMAS.MMVOL3        AS ORDERQTY_L,
        MPDOPE.POPITI                      AS RUNTIME,
        MPDOPE.POCTCD                      AS EFFICIENCY,
        MPDOPE.POPRNP                      AS FILLING_PEOPLE,
        MPDOPE.POSETI                      AS SETUP_TIME,
        MPDOPE.POSENP                      AS SETUP_PEOPLE,
        ROUND(
            CASE
                WHEN MPDOPE.POCTCD = 0 OR MITMAS.MMVOL3 = 0 THEN 0
                ELSE (((MPDOPE.POPITI / MPDOPE.POCTCD::NUMERIC) / MITMAS.MMVOL3) * 1000)
            END
        , 6)                               AS FILL_MH_1000L,
        ROUND(
            CASE
                WHEN MPDOPE.POCTCD = 0 OR MITMAS.MMVOL3 = 0 THEN 0
                ELSE ((((MPDOPE.POPRNP * MPDOPE.POPITI) / MPDOPE.POCTCD::NUMERIC) / MITMAS.MMVOL3) * 1000)
            END
        , 6)                               AS FILL_LH_1000L,
        ROUND(
            CASE
                WHEN MB1.MBEOQT = 0 OR MPDOPE.POSETI = 0 OR MITMAS.MMVOL3 = 0 THEN 0
                ELSE (((MPDOPE.POSETI / MB1.MBEOQT) / MITMAS.MMVOL3) * 1000)
            END
        , 6)                               AS SETUP_MH_1000L,
        ROUND(
            CASE
                WHEN MB1.MBEOQT = 0 OR MPDOPE.POSETI = 0 OR MITMAS.MMVOL3 = 0 THEN 0
                ELSE ((((MPDOPE.POSETI * MPDOPE.POSENP) / MB1.MBEOQT) / MITMAS.MMVOL3) * 1000)
            END
        , 6)                               AS SETUP_LH_1000L
    FROM MVXJDTA.MPDOPE MPDOPE
    JOIN MVXJDTA.MITMAS MITMAS
        ON MITMAS.MMCONO = 100
       AND MITMAS.MMITNO = MPDOPE.POPRNO
    LEFT JOIN MVXJDTA.MITFAC MITFAC
        ON MITFAC.M9CONO = MITMAS.MMCONO
       AND MITFAC.M9FACI = MPDOPE.POFACI
       AND MITFAC.M9ITNO = MITMAS.MMITNO
    LEFT JOIN MVXJDTA.MITBAL MB1
        ON MB1.MBCONO = MITFAC.M9CONO
       AND MB1.MBITNO = MITMAS.MMITNO
       AND MB1.MBWHLO = MITFAC.M9REWH
    WHERE MPDOPE.POCONO = 100
      AND MPDOPE.POFACI <> '800'
      AND MPDOPE.POSTRT IN ('100','106')
      AND MPDOPE.POSDCD = 1
      AND MITMAS.MMITY IN ('10','40')
      AND MITMAS.MMSTAT <= '20'
)

SELECT
    DIVISION,
    PRODUCT        AS PRODUCT_CODE,
    PRODUCTIONLINE AS WC_CODE,
    FILL_MH_1000L,
    FILL_LH_1000L,
    SETUP_MH_1000L,
    SETUP_LH_1000L,
    ORDERQTY_L,
    SETUP_TIME,
    SETUP_PEOPLE
FROM CTE_OPERATIONS
WHERE DIVISION NOT IN ('800','400')

UNION ALL

SELECT
    DIVISION,
    PRODUCT_CODE,
    WC_CODE,
    FILL_MH_1000L,
    FILL_LH_1000L,
    SETUP_MH_1000L,
    SETUP_LH_1000L,
    ORDERQTY_L,
    SETUP_TIME,
    SETUP_PEOPLE
FROM LIDSKOE.TD_COGS_OPERATIONS
WHERE DIVISION = '800'

UNION ALL

SELECT
    DIVISION,
    PRODUCT_CODE,
    WC_CODE,
    FILL_MH_1000L,
    FILL_LH_1000L,
    SETUP_MH_1000L,
    SETUP_LH_1000L,
    ORDERQTY_L,
    SETUP_TIME,
    SETUP_PEOPLE
FROM M3SKY.TD_COGS_OPERATIONS
WHERE DIVISION = '400';