CREATE OR REPLACE VIEW ANAPLAN.TD_MARKETINGMONEY AS
WITH
CTE_CUSTOMER_CONVERSION AS (
    SELECT DIVI, OLDCUSTOMER, NEWCUSTOMER
    FROM ANAPLAN.AD_CUSTOMER_CONVERSION
),
CTE_CUSTOMER_DETAIL AS (
    SELECT
        DIVISION,
        L1_REGION,
        L2_SALESCHANNEL,
        L3_CODE,
        L4_CODE,
        L5_CODE,
        L6_CODE,
        M3CUSTOMERCODE
    FROM ANAPLAN.MD_CUSTOMER_DETAIL_T
),
CTE_ADJUSTMENTS AS (
    SELECT
        bodivi,
        boperi,
        CASE WHEN CV.NEWCUSTOMER IS NULL THEN bocuno ELSE CV.NEWCUSTOMER END AS bocuno,
        SUM(boboam) AS boboam,
        boitno
    FROM bousr.prep_salesadjustments
    LEFT JOIN CTE_CUSTOMER_CONVERSION CV
        ON bodivi = CV.DIVI
       AND bocuno = CV.OLDCUSTOMER
    WHERE boptype = 'MARKETINGM'
      AND bodivi NOT IN ('800','400')
      AND boperi::TEXT >= TO_CHAR(CURRENT_DATE - INTERVAL '1 month','YYYYMM')
    GROUP BY
        bodivi,
        boperi,
        CASE WHEN CV.NEWCUSTOMER IS NULL THEN bocuno ELSE CV.NEWCUSTOMER END,
        boitno
),
CTE_DOMESTIC_MARKETINGMONEY AS (
    SELECT
        CAST(ADJ.bodivi AS VARCHAR(3)) AS DIVISION,
        CAST(ADJ.boperi AS VARCHAR(6)) AS PERIOD,
        CAST(ADJ.bodivi || '-' || CU.L1_REGION AS VARCHAR(108)) AS L1_REGION,
        CAST(ADJ.bodivi || '-' || CU.L2_SALESCHANNEL AS VARCHAR(108)) AS L2_SALESCHANNEL,
        ADJ.bodivi || '-' || CU.L2_SALESCHANNEL || '-' || CU.L3_CODE AS L3_CODE,
        ADJ.bodivi || '-' || CU.L2_SALESCHANNEL || '-' || CU.L3_CODE || '-' || CU.L4_CODE AS L4_CODE,
        ADJ.bodivi || '-' || CU.L2_SALESCHANNEL || '-' || CU.L3_CODE || '-' || CU.L4_CODE
            || CASE WHEN CU.L5_CODE = CU.L4_CODE THEN '' ELSE '-' || CU.L5_CODE END
            || '-' || CU.L6_CODE AS L5_CODE,
        SUM(ADJ.boboam) AS AMOUNT,
        ADJ.boitno AS ITEM_CODE
    FROM CTE_ADJUSTMENTS ADJ
    LEFT JOIN CTE_CUSTOMER_DETAIL CU
        ON ADJ.bodivi = CU.DIVISION
       AND ADJ.bocuno = CU.M3CUSTOMERCODE
    GROUP BY
        ADJ.bodivi,
        ADJ.boperi,
        CU.L1_REGION,
        CU.L2_SALESCHANNEL,
        CU.L3_CODE,
        CU.L4_CODE,
        CU.L5_CODE,
        CU.L6_CODE,
        ADJ.boitno
),
CTE_LIDSKOE_800 AS (
    SELECT
        DIVISION,
        PERIOD,
        L1_REGION,
        L2_SALESCHANNEL,
        L3_CODE,
        L4_CODE,
        L5_CODE,
        AMOUNT,
        ITEM_CODE
    FROM LIDSKOE.TD_MARKETINGMONEY
    WHERE DIVISION = '800'
),
CTE_M3SKY_400 AS (
    SELECT
        DIVISION,
        PERIOD,
        L1_REGION,
        L2_SALESCHANNEL,
        L3_CODE,
        L4_CODE,
        L5_CODE,
        AMOUNT,
        ITEM_CODE
    FROM M3SKY.TD_MARKETINGMONEY
    WHERE DIVISION = '400'
)
SELECT DIVISION, PERIOD, L1_REGION, L2_SALESCHANNEL, L3_CODE, L4_CODE, L5_CODE, AMOUNT, ITEM_CODE
FROM CTE_DOMESTIC_MARKETINGMONEY
UNION ALL
SELECT DIVISION, PERIOD, L1_REGION, L2_SALESCHANNEL, L3_CODE, L4_CODE, L5_CODE, AMOUNT, ITEM_CODE
FROM CTE_LIDSKOE_800
UNION ALL
SELECT DIVISION, PERIOD, L1_REGION, L2_SALESCHANNEL, L3_CODE, L4_CODE, L5_CODE, AMOUNT, ITEM_CODE
FROM CTE_M3SKY_400;

COMMENT ON VIEW ANAPLAN.TD_MARKETINGMONEY IS
    'CTE-standardized TD marketing money view. Uses ANAPLAN.MD_CUSTOMER_DETAIL_T and ANAPLAN.AD_CUSTOMER_CONVERSION tables; preserves BOUSR sources and unions compatibility data from LIDSKOE/M3SKY.';