-- =============================================================================
-- TABLE: ref.WORKCENTER_GROUP
-- Replaces: Large CASE WHEN ppplgr IN (...) THEN group in MD_WORKCENTER + MD_PRODUCT
-- Used by:  md_workcenter_v, md_product_v
-- =============================================================================
CREATE TABLE IF NOT EXISTS ref.WORKCENTER_GROUP (
    PPPLGR           VARCHAR(20) NOT NULL PRIMARY KEY,
    WORKCENTER_GROUP VARCHAR(50) NOT NULL
);

TRUNCATE ref.WORKCENTER_GROUP;
INSERT INTO ref.WORKCENTER_GROUP (PPPLGR, WORKCENTER_GROUP) VALUES
    ('6','FILLING'),('8','FILLING'),('10','FILLING'),('11','FILLING'),('12','FILLING'),
    ('13','FILLING'),('14','FILLING'),('20','FILLING'),('ÕLU','FILLING'),
    ('KLAAS','FILLING'),('VAAT','FILLING'),('PURK','FILLING'),('PET2','FILLING'),
    ('TETRA','FILLING'),('TETRA3','FILLING'),
    ('705','FILLING'),('706','FILLING'),('707','FILLING'),('711','FILLING'),
    ('605','FILLING'),('606','FILLING'),('607','FILLING'),('611','FILLING'),
    ('612','FILLING'),('614','FILLING'),('632','FILLING'),('650','FILLING'),('660','FILLING'),
    ('411','FILLING'),('412','FILLING'),('413','FILLING'),('414','FILLING'),
    ('415','FILLING'),('416','FILLING'),('431','FILLING'),('435','FILLING'),
    ('KL.MP','MULTIPACKING & REPACKING'),('610','MULTIPACKING & REPACKING'),
    ('418','MULTIPACKING & REPACKING'),('709','MULTIPACKING & REPACKING'),
    ('710','MULTIPACKING & REPACKING'),('712','MULTIPACKING & REPACKING'),
    ('419','MULTIPACKING & REPACKING'),('420','MULTIPACKING & REPACKING'),
    ('450','MULTIPACKING & REPACKING'),
    ('101','BOILING AND MIXING'),('102','BOILING AND MIXING'),('103','BOILING AND MIXING'),
    ('104','BOILING AND MIXING'),('108','BOILING AND MIXING'),('109','BOILING AND MIXING'),
    ('201','BOILING AND MIXING'),('202','BOILING AND MIXING'),('204','BOILING AND MIXING'),
    ('205','BOILING AND MIXING'),('206','BOILING AND MIXING'),('207','BOILING AND MIXING'),
    ('305','BOILING AND MIXING'),('315','BOILING AND MIXING'),
    ('701','BOILING AND MIXING'),('702','BOILING AND MIXING'),('703','BOILING AND MIXING'),
    ('704','BOILING AND MIXING'),('708','BOILING AND MIXING'),
    ('601','BOILING AND MIXING'),('602','BOILING AND MIXING'),('604','BOILING AND MIXING'),
    ('608','BOILING AND MIXING'),('609','BOILING AND MIXING'),('625','BOILING AND MIXING'),
    ('630','BOILING AND MIXING'),('631','BOILING AND MIXING'),
    ('401','BOILING AND MIXING'),('402','BOILING AND MIXING'),('404','BOILING AND MIXING'),
    ('407','BOILING AND MIXING'),('421','BOILING AND MIXING'),('422','BOILING AND MIXING'),
    ('423','BOILING AND MIXING'),('424','BOILING AND MIXING'),('425','BOILING AND MIXING'),
    ('427','BOILING AND MIXING');

COMMENT ON TABLE ref.WORKCENTER_GROUP IS
    'Workcenter group lookup. Replaces large CASE WHEN ppplgr IN (...) Oracle logic in MD_WORKCENTER + MD_PRODUCT.';
