
--AD_CUSTOMER_CONVERSION



  CREATE TABLE "ANAPLAN"."AD_CUSTOMER_CONVERSION" 
   (	"DIVI" VARCHAR2(3 BYTE) NOT NULL ENABLE, 
	"OLDCUSTOMER" VARCHAR2(11 BYTE) NOT NULL ENABLE, 
	"NEWCUSTOMER" VARCHAR2(11 BYTE) NOT NULL ENABLE, 
	"TXTCOMMENT" VARCHAR2(85 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


  GRANT SELECT ON "ANAPLAN"."AD_CUSTOMER_CONVERSION" TO "LOTMAT";
  GRANT SELECT ON "ANAPLAN"."AD_CUSTOMER_CONVERSION" TO "KAPRIS";
  GRANT SELECT ON "ANAPLAN"."AD_CUSTOMER_CONVERSION" TO "BOUSR";



--AD_LAST_PURCH_PRICE

  CREATE TABLE "ANAPLAN"."AD_LAST_PURCH_PRICE" 
   (	"DIVISION" VARCHAR2(9 BYTE) NOT NULL ENABLE, 
	"SUPPLIER" VARCHAR2(108 BYTE), 
	"L4_CODE" VARCHAR2(45 BYTE) NOT NULL ENABLE, 
	"CURRENCY" VARCHAR2(9 BYTE) NOT NULL ENABLE, 
	"PURCHDATE" NUMBER, 
	"PRICE_CURR" NUMBER, 
	"CHARGE_LOCCURR" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


  GRANT SELECT ON "ANAPLAN"."AD_LAST_PURCH_PRICE" TO "LOTMAT";
  GRANT SELECT ON "ANAPLAN"."AD_LAST_PURCH_PRICE" TO "KAPRIS";


--AD_MARKET_DATA


  CREATE TABLE "ANAPLAN"."AD_MARKET_DATA" 
   (	"DIVI" VARCHAR2(3 BYTE), 
	"IVDT" VARCHAR2(10 BYTE), 
	"CATEGORY" VARCHAR2(28 BYTE), 
	"VOLUME" NUMBER(15,7)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


  GRANT SELECT ON "ANAPLAN"."AD_MARKET_DATA" TO "LOTMAT";
  GRANT SELECT ON "ANAPLAN"."AD_MARKET_DATA" TO "KAPRIS";


--ANAP_CURRENCYRATES


  CREATE TABLE "ANAPLAN"."ANAP_CURRENCYRATES" 
   (	"COMPANY" VARCHAR2(100 BYTE), 
	"TIME" VARCHAR2(20 BYTE), 
	"VERSIONS" VARCHAR2(30 BYTE), 
	"DIVI" VARCHAR2(30 BYTE), 
	"LOCALCURRENCY" VARCHAR2(3 BYTE), 
	"PERIOD" VARCHAR2(6 BYTE), 
	"AVERAGE_RATE" VARCHAR2(35 BYTE), 
	"CLOSING_RATE" VARCHAR2(35 BYTE), 
	"DATATYPE" VARCHAR2(15 BYTE)
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "CSV_DIR"
      ACCESS PARAMETERS
      ( records delimited by newline
       skip 1 
       fields terminated by "," lrtrim
       missing field values are null
     )
      LOCATION
       ( '116000000011.csv'
       )
    )
   REJECT LIMIT UNLIMITED 
  PARALLEL 5 ;


  GRANT SELECT ON "ANAPLAN"."ANAP_CURRENCYRATES" TO "LOTMAT";
  GRANT SELECT ON "ANAPLAN"."ANAP_CURRENCYRATES" TO "BOUSR";
  GRANT SELECT ON "ANAPLAN"."ANAP_CURRENCYRATES" TO "KAPRIS";


--AVG_PRICE_UNTIL


  CREATE TABLE "ANAPLAN"."AVG_PRICE_UNTIL" 
   (	"FACILITY" VARCHAR2(9 BYTE) NOT NULL ENABLE, 
	"SKU" VARCHAR2(45 BYTE) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(180 BYTE) NOT NULL ENABLE, 
	"ON_HAND_BALANCE" NUMBER(15,6) NOT NULL ENABLE, 
	"AVG_COST" NUMBER(17,6) NOT NULL ENABLE, 
	"AVG_COST_UNTIL" NUMBER(8,0), 
	"AVG_UNTIL_PERIOD" VARCHAR2(6 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE UNIQUE INDEX "ANAPLAN"."AVG_PRICE_UNTIL00" ON "ANAPLAN"."AVG_PRICE_UNTIL" ("FACILITY", "SKU") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


  GRANT SELECT ON "ANAPLAN"."AVG_PRICE_UNTIL" TO "KAPRIS";


--F116000000000

  CREATE TABLE "ANAPLAN"."F116000000000" 
   (	"CONO" VARCHAR2(3 BYTE), 
	"DIVI" VARCHAR2(3 BYTE), 
	"WHLO" VARCHAR2(3 BYTE), 
	"ITNO" VARCHAR2(35 BYTE), 
	"VOL3" VARCHAR2(35 BYTE)
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "CSV_DIR"
      ACCESS PARAMETERS
      ( records delimited by newline
       skip 1 
       fields terminated by "|" lrtrim
       missing field values are null
     )
      LOCATION
       ( '116000000000.csv'
       )
    )
   REJECT LIMIT UNLIMITED 
  PARALLEL 5 ;


  GRANT SELECT ON "ANAPLAN"."F116000000000" TO "LOTMAT";
  GRANT SELECT ON "ANAPLAN"."F116000000000" TO "KAPRIS";


--F116000000004


  CREATE TABLE "ANAPLAN"."F116000000004" 
   (	"Materials_L4_Materials_SS_Code" NVARCHAR2(100), 
	"Time" NVARCHAR2(38), 
	"COMPANYCODE" NVARCHAR2(38), 
	"DIVISION" NVARCHAR2(38), 
	"PERIOD" NUMBER(6,0), 
	"ITEMCODE" NVARCHAR2(45), 
	"QUANTITY" NUMBER(38,6), 
	"PRICE" NUMBER(38,6), 
	"PRICE_PURE" NUMBER(38,6), 
	"PRICE_AVG" NUMBER(38,6), 
	"CURR_RATE" NUMBER(10,4)
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "CSV_DIR"
      ACCESS PARAMETERS
      ( records delimited by newline
        skip 1 
        fields terminated by "," lrtrim
        missing field values are null
    )
      LOCATION
       ( '116000000004.csv'
       )
    )
   REJECT LIMIT UNLIMITED 
  PARALLEL 5 ;


  GRANT SELECT ON "ANAPLAN"."F116000000004" TO "LOTMAT";
  GRANT SELECT ON "ANAPLAN"."F116000000004" TO "BOUSR";
  GRANT SELECT ON "ANAPLAN"."F116000000004" TO "KAPRIS";
  
  
 --F116000000005
 
 
  CREATE TABLE "ANAPLAN"."F116000000005" 
   (	"CONO" VARCHAR2(3 BYTE), 
	"DIVI" VARCHAR2(3 BYTE), 
	"WHLO" VARCHAR2(3 BYTE), 
	"ITNO" VARCHAR2(35 BYTE), 
	"FROMDATE" VARCHAR2(35 BYTE), 
	"TODATE" VARCHAR2(35 BYTE), 
	"VOL3" VARCHAR2(35 BYTE)
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "CSV_DIR"
      ACCESS PARAMETERS
      ( records delimited by newline
       skip 1 
       fields terminated by "|" lrtrim
       missing field values are null
     )
      LOCATION
       ( '116000000005.csv'
       )
    )
   REJECT LIMIT UNLIMITED 
  PARALLEL 5 ;


  GRANT SELECT ON "ANAPLAN"."F116000000005" TO "LOTMAT";
  GRANT ALTER ON "ANAPLAN"."F116000000005" TO PUBLIC;
  GRANT SELECT ON "ANAPLAN"."F116000000005" TO PUBLIC;
  GRANT READ ON "ANAPLAN"."F116000000005" TO PUBLIC;
  GRANT SELECT ON "ANAPLAN"."F116000000005" TO "KAPRIS";
  
  
 --F116000000009
 

  CREATE TABLE "ANAPLAN"."F116000000009" 
   (	"ITEM" VARCHAR2(35 BYTE), 
	"CUSTOMERS" VARCHAR2(35 BYTE), 
	"DAY" VARCHAR2(10 BYTE), 
	"VERSION" VARCHAR2(35 BYTE), 
	"FORECAST" VARCHAR2(35 BYTE), 
	"VALUE" VARCHAR2(35 BYTE)
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "CSV_DIR"
      ACCESS PARAMETERS
      ( records delimited by newline
       skip 1 
       fields terminated by "," lrtrim
       missing field values are null
     )
      LOCATION
       ( '116000000009.csv'
       )
    )
   REJECT LIMIT UNLIMITED 
  PARALLEL 5 ;


  GRANT SELECT ON "ANAPLAN"."F116000000009" TO "BOUSR";
  GRANT SELECT ON "ANAPLAN"."F116000000009" TO "LOTMAT";
  GRANT SELECT ON "ANAPLAN"."F116000000009" TO "KAPRIS";


--F116000000022


  CREATE TABLE "ANAPLAN"."F116000000022" 
   (	"CONO" VARCHAR2(3 BYTE), 
	"DIVI" VARCHAR2(3 BYTE), 
	"WHLO" VARCHAR2(3 BYTE), 
	"ITNO" VARCHAR2(35 BYTE), 
	"FDAT" VARCHAR2(35 BYTE), 
	"TDAT" VARCHAR2(35 BYTE), 
	"VOL3" VARCHAR2(35 BYTE)
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "CSV_DIR"
      ACCESS PARAMETERS
      ( records delimited by newline
                   skip 1 
                   fields terminated by "|" lrtrim
                   missing field values are null 
)
      LOCATION
       ( "CSV_DIR":'116000000022.csv'
       )
    )
   REJECT LIMIT UNLIMITED 
  PARALLEL 5 ;


  GRANT SELECT ON "ANAPLAN"."F116000000022" TO "BOUSR";
  GRANT SELECT ON "ANAPLAN"."F116000000022" TO "LOTMAT";
  GRANT SELECT ON "ANAPLAN"."F116000000022" TO "KAPRIS";


--F116000000023


  CREATE TABLE "ANAPLAN"."F116000000023" 
   (	"CONO" VARCHAR2(3 BYTE), 
	"DIVI" VARCHAR2(3 BYTE), 
	"WHLO" VARCHAR2(3 BYTE), 
	"ITNO" VARCHAR2(35 BYTE), 
	"FDAT" VARCHAR2(35 BYTE), 
	"TDAT" VARCHAR2(35 BYTE), 
	"VOL3" VARCHAR2(35 BYTE)
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "CSV_DIR"
      ACCESS PARAMETERS
      ( records delimited by newline
                   skip 1 
                   fields terminated by "|" lrtrim
                   missing field values are null 
    )
      LOCATION
       ( "CSV_DIR":'116000000023.csv'
       )
    )
   REJECT LIMIT UNLIMITED 
  PARALLEL 5 ;


  GRANT SELECT ON "ANAPLAN"."F116000000023" TO "BOUSR";
  GRANT SELECT ON "ANAPLAN"."F116000000023" TO "LOTMAT";
  GRANT SELECT ON "ANAPLAN"."F116000000023" TO "KAPRIS";


--F116000000048


  CREATE TABLE "ANAPLAN"."F116000000048" 
   (	"TIME" VARCHAR2(35 BYTE), 
	"DIVISION" VARCHAR2(35 BYTE), 
	"PERIOD" VARCHAR2(35 BYTE), 
	"DATATYPE" VARCHAR2(35 BYTE), 
	"PRODUCT_CODE" VARCHAR2(35 BYTE), 
	"MATERIAL_CODE" VARCHAR2(35 BYTE), 
	"COST_COMPONENT" VARCHAR2(35 BYTE), 
	"QTY_1000L" VARCHAR2(35 BYTE), 
	"PRICE" VARCHAR2(35 BYTE), 
	"COST_L" VARCHAR2(35 BYTE)
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "CSV_DIR"
      ACCESS PARAMETERS
      ( records delimited by newline
                   skip 1 
                   fields terminated by "," lrtrim
                   missing field values are null 
            )
      LOCATION
       ( "CSV_DIR":'116000000048.csv'
       )
    )
   REJECT LIMIT UNLIMITED 
  PARALLEL 5 ;


  GRANT ALTER ON "ANAPLAN"."F116000000048" TO "BOUSR" WITH GRANT OPTION;
  GRANT SELECT ON "ANAPLAN"."F116000000048" TO "BOUSR" WITH GRANT OPTION;
  GRANT READ ON "ANAPLAN"."F116000000048" TO "BOUSR" WITH GRANT OPTION;


--F116000000049


  CREATE TABLE "ANAPLAN"."F116000000049" 
   (	"TIME" VARCHAR2(35 BYTE), 
	"DIVISION" VARCHAR2(35 BYTE), 
	"PERIOD" VARCHAR2(35 BYTE), 
	"DATATYPE" VARCHAR2(35 BYTE), 
	"PRODUCT_CODE" VARCHAR2(35 BYTE), 
	"MATERIAL_CODE" VARCHAR2(35 BYTE), 
	"COST_COMPONENT" VARCHAR2(35 BYTE), 
	"QTY_1000L" VARCHAR2(35 BYTE), 
	"PRICE" VARCHAR2(35 BYTE), 
	"COST_L" VARCHAR2(35 BYTE)
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "CSV_DIR"
      ACCESS PARAMETERS
      ( records delimited by newline
                   skip 1 
                   fields terminated by "," lrtrim
                   missing field values are null 
        )
      LOCATION
       ( "CSV_DIR":'116000000049.csv'
       )
    )
   REJECT LIMIT UNLIMITED 
  PARALLEL 5 ;


  GRANT ALTER ON "ANAPLAN"."F116000000049" TO "BOUSR";
  GRANT SELECT ON "ANAPLAN"."F116000000049" TO "BOUSR";
  GRANT READ ON "ANAPLAN"."F116000000049" TO "BOUSR";


--HTTP_BLOB_TEST


  CREATE TABLE "ANAPLAN"."HTTP_BLOB_TEST" 
   (	"ID" NUMBER(10,0), 
	"URL" VARCHAR2(255 BYTE), 
	"DATA" CLOB, 
	 CONSTRAINT "HTTP_BLOB_TEST_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("DATA") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;


  GRANT SELECT ON "ANAPLAN"."HTTP_BLOB_TEST" TO "LOTMAT";
  GRANT SELECT ON "ANAPLAN"."HTTP_BLOB_TEST" TO "KAPRIS";


--LAST_PURCH_PRICE


  CREATE TABLE "ANAPLAN"."LAST_PURCH_PRICE" 
   (	"DIVISION" VARCHAR2(9 BYTE) NOT NULL ENABLE, 
	"SUPPLIER" VARCHAR2(108 BYTE), 
	"L4_CODE" VARCHAR2(45 BYTE) NOT NULL ENABLE, 
	"CURRENCY" VARCHAR2(9 BYTE) NOT NULL ENABLE, 
	"PURCHDATE" NUMBER, 
	"PRICE_CURR" NUMBER, 
	"CHARGE_LOCCURR" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


  GRANT SELECT ON "ANAPLAN"."LAST_PURCH_PRICE" TO "LOTMAT";
  GRANT SELECT ON "ANAPLAN"."LAST_PURCH_PRICE" TO "KAPRIS";


--LAST_PURCHASE_PRICE


  CREATE TABLE "ANAPLAN"."LAST_PURCHASE_PRICE" 
   (	"DIVISION" VARCHAR2(3 BYTE), 
	"SUPPLIER" VARCHAR2(34 BYTE), 
	"L4_CODE" VARCHAR2(7 BYTE), 
	"CURRENCY" VARCHAR2(3 BYTE), 
	"PURCHDATE" NUMBER(8,0), 
	"PRICE_CURR" NUMBER(17,7), 
	"CHARGE_LOCCURR" NUMBER(15,7)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


  GRANT SELECT ON "ANAPLAN"."LAST_PURCHASE_PRICE" TO "LOTMAT";
  GRANT SELECT ON "ANAPLAN"."LAST_PURCHASE_PRICE" TO "KAPRIS";


--MD_BUDGET_CUSTOMER


  CREATE TABLE "ANAPLAN"."MD_BUDGET_CUSTOMER" 
   (	"DIVISION" VARCHAR2(3 BYTE), 
	"LOCAL_REGION" VARCHAR2(6 BYTE), 
	"CUSTOMERCODE" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


  GRANT SELECT ON "ANAPLAN"."MD_BUDGET_CUSTOMER" TO "LOTMAT";
  GRANT SELECT ON "ANAPLAN"."MD_BUDGET_CUSTOMER" TO "KAPRIS";


--MD_BUDGET_CUSTOMER_200


  CREATE TABLE "ANAPLAN"."MD_BUDGET_CUSTOMER_200" 
   (	"DIVISION" VARCHAR2(3 BYTE), 
	"LOCAL_REGION" VARCHAR2(6 BYTE), 
	"DISTRICT" VARCHAR2(6 BYTE), 
	"CUSTOMERCODE" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


  GRANT SELECT ON "ANAPLAN"."MD_BUDGET_CUSTOMER_200" TO "KAPRIS";


--MD_CUSTOMER_DETAIL_T


  CREATE TABLE "ANAPLAN"."MD_CUSTOMER_DETAIL_T" 
   (	"DIVISION" VARCHAR2(108 BYTE), 
	"L1_REGION" VARCHAR2(108 BYTE), 
	"L2_SALESCHANNEL" VARCHAR2(108 BYTE), 
	"L3_CUSTOMERGROUP" VARCHAR2(108 BYTE), 
	"L4_CHAIN" VARCHAR2(108 BYTE), 
	"L5_CUSTOMER" VARCHAR2(108 BYTE), 
	"L6_EXCISE_DEPO" VARCHAR2(108 BYTE), 
	"L3_CODE" VARCHAR2(108 BYTE), 
	"L4_CODE" VARCHAR2(108 BYTE), 
	"L5_CODE" VARCHAR2(108 BYTE), 
	"L6_CODE" VARCHAR2(108 BYTE), 
	"EXC_TMP" VARCHAR2(3 BYTE), 
	"DEP_TMP" VARCHAR2(3 BYTE), 
	"SHOP" VARCHAR2(108 BYTE), 
	"CHARGEMODEL" VARCHAR2(108 BYTE), 
	"M3CUSTOMERCODE" VARCHAR2(108 BYTE), 
	"M3STATUS" VARCHAR2(108 BYTE), 
	"EXCISE" VARCHAR2(3 BYTE), 
	"DEPOFEE" VARCHAR2(3 BYTE), 
	"PRICELIST_REF" VARCHAR2(108 BYTE), 
	"BONUSGROUP_REF" VARCHAR2(108 BYTE), 
	"DISCOUNTGROUP_REF" VARCHAR2(108 BYTE), 
	"DELIVERYGROUP" VARCHAR2(108 BYTE), 
	"DELIVERYGROUP_CODE" VARCHAR2(108 BYTE), 
	"LOCAL_REGION" VARCHAR2(24 BYTE), 
	"SALESPERSON" VARCHAR2(30 BYTE), 
	"BUDGET_CUSTOMERCODE" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


  GRANT SELECT ON "ANAPLAN"."MD_CUSTOMER_DETAIL_T" TO "LOTMAT";
  GRANT SELECT ON "ANAPLAN"."MD_CUSTOMER_DETAIL_T" TO "BOUSR";
  GRANT SELECT ON "ANAPLAN"."MD_CUSTOMER_DETAIL_T" TO "KAPRIS";



--OL_FIXEDDISCOUNTS

  CREATE TABLE "ANAPLAN"."OL_FIXEDDISCOUNTS" 
   (	"VFCONT" VARCHAR2(30 BYTE), 
	"VFCUNO" VARCHAR2(30 BYTE), 
	"VFITNO" VARCHAR2(45 BYTE), 
	"VFIVDT" NUMBER(8,0), 
	"VFSAAM" NUMBER(15,2), 
	"VFSYTP" VARCHAR2(100 BYTE), 
	"VFDIVI" VARCHAR2(9 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


  GRANT SELECT ON "ANAPLAN"."OL_FIXEDDISCOUNTS" TO "LOTMAT";
  GRANT ALTER ON "ANAPLAN"."OL_FIXEDDISCOUNTS" TO "BOUSR";
  GRANT DELETE ON "ANAPLAN"."OL_FIXEDDISCOUNTS" TO "BOUSR";
  GRANT INDEX ON "ANAPLAN"."OL_FIXEDDISCOUNTS" TO "BOUSR";
  GRANT INSERT ON "ANAPLAN"."OL_FIXEDDISCOUNTS" TO "BOUSR";
  GRANT SELECT ON "ANAPLAN"."OL_FIXEDDISCOUNTS" TO "BOUSR";
  GRANT UPDATE ON "ANAPLAN"."OL_FIXEDDISCOUNTS" TO "BOUSR";
  GRANT REFERENCES ON "ANAPLAN"."OL_FIXEDDISCOUNTS" TO "BOUSR";
  GRANT READ ON "ANAPLAN"."OL_FIXEDDISCOUNTS" TO "BOUSR";
  GRANT ON COMMIT REFRESH ON "ANAPLAN"."OL_FIXEDDISCOUNTS" TO "BOUSR";
  GRANT QUERY REWRITE ON "ANAPLAN"."OL_FIXEDDISCOUNTS" TO "BOUSR";
  GRANT DEBUG ON "ANAPLAN"."OL_FIXEDDISCOUNTS" TO "BOUSR";
  GRANT FLASHBACK ON "ANAPLAN"."OL_FIXEDDISCOUNTS" TO "BOUSR";
  GRANT ALTER ON "ANAPLAN"."OL_FIXEDDISCOUNTS" TO PUBLIC;
  GRANT DELETE ON "ANAPLAN"."OL_FIXEDDISCOUNTS" TO PUBLIC;
  GRANT INDEX ON "ANAPLAN"."OL_FIXEDDISCOUNTS" TO PUBLIC;
  GRANT INSERT ON "ANAPLAN"."OL_FIXEDDISCOUNTS" TO PUBLIC;
  GRANT SELECT ON "ANAPLAN"."OL_FIXEDDISCOUNTS" TO PUBLIC;
  GRANT UPDATE ON "ANAPLAN"."OL_FIXEDDISCOUNTS" TO PUBLIC;
  GRANT REFERENCES ON "ANAPLAN"."OL_FIXEDDISCOUNTS" TO PUBLIC;
  GRANT READ ON "ANAPLAN"."OL_FIXEDDISCOUNTS" TO PUBLIC;
  GRANT ON COMMIT REFRESH ON "ANAPLAN"."OL_FIXEDDISCOUNTS" TO PUBLIC;
  GRANT QUERY REWRITE ON "ANAPLAN"."OL_FIXEDDISCOUNTS" TO PUBLIC;
  GRANT DEBUG ON "ANAPLAN"."OL_FIXEDDISCOUNTS" TO PUBLIC;
  GRANT FLASHBACK ON "ANAPLAN"."OL_FIXEDDISCOUNTS" TO PUBLIC;
  GRANT SELECT ON "ANAPLAN"."OL_FIXEDDISCOUNTS" TO "KAPRIS";



--OL_SALESINVOICEDISCOUNTS


  CREATE TABLE "ANAPLAN"."OL_SALESINVOICEDISCOUNTS" 
   (	"VAITNO" VARCHAR2(45 BYTE), 
	"VASAAM" NUMBER(15,3), 
	"VAVOL3" NUMBER(15,3), 
	"VAOVQT" NUMBER(15,3), 
	"VAEXCI" NUMBER(15,3), 
	"VAINVO" NUMBER(15,3), 
	"VAINPR" NUMBER(15,3), 
	"VACBVO" NUMBER(15,3), 
	"VACAPR" NUMBER(15,3), 
	"VAMAVO" NUMBER(15,3), 
	"VAMAPR" NUMBER(15,3), 
	"VACOVO" NUMBER(15,3), 
	"VACOPR" NUMBER(15,3), 
	"VAMAEU" NUMBER(15,3), 
	"VASMVO" NUMBER(15,3), 
	"VASCBV" NUMBER(15,3), 
	"VASDIV" NUMBER(15,3), 
	"VASMAV" NUMBER(15,3), 
	"VASCBP" NUMBER(15,3), 
	"VASDIP" NUMBER(15,3), 
	"VAACRF" VARCHAR2(100 BYTE), 
	"VAYEMO" NUMBER(15,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


  GRANT ALTER ON "ANAPLAN"."OL_SALESINVOICEDISCOUNTS" TO PUBLIC;
  GRANT DELETE ON "ANAPLAN"."OL_SALESINVOICEDISCOUNTS" TO PUBLIC;
  GRANT INDEX ON "ANAPLAN"."OL_SALESINVOICEDISCOUNTS" TO PUBLIC;
  GRANT INSERT ON "ANAPLAN"."OL_SALESINVOICEDISCOUNTS" TO PUBLIC;
  GRANT SELECT ON "ANAPLAN"."OL_SALESINVOICEDISCOUNTS" TO PUBLIC;
  GRANT UPDATE ON "ANAPLAN"."OL_SALESINVOICEDISCOUNTS" TO PUBLIC;
  GRANT REFERENCES ON "ANAPLAN"."OL_SALESINVOICEDISCOUNTS" TO PUBLIC;
  GRANT READ ON "ANAPLAN"."OL_SALESINVOICEDISCOUNTS" TO PUBLIC;
  GRANT ON COMMIT REFRESH ON "ANAPLAN"."OL_SALESINVOICEDISCOUNTS" TO PUBLIC;
  GRANT QUERY REWRITE ON "ANAPLAN"."OL_SALESINVOICEDISCOUNTS" TO PUBLIC;
  GRANT DEBUG ON "ANAPLAN"."OL_SALESINVOICEDISCOUNTS" TO PUBLIC;
  GRANT FLASHBACK ON "ANAPLAN"."OL_SALESINVOICEDISCOUNTS" TO PUBLIC;
  GRANT ALTER ON "ANAPLAN"."OL_SALESINVOICEDISCOUNTS" TO "BOUSR";
  GRANT DELETE ON "ANAPLAN"."OL_SALESINVOICEDISCOUNTS" TO "BOUSR";
  GRANT INDEX ON "ANAPLAN"."OL_SALESINVOICEDISCOUNTS" TO "BOUSR";
  GRANT INSERT ON "ANAPLAN"."OL_SALESINVOICEDISCOUNTS" TO "BOUSR";
  GRANT SELECT ON "ANAPLAN"."OL_SALESINVOICEDISCOUNTS" TO "BOUSR";
  GRANT UPDATE ON "ANAPLAN"."OL_SALESINVOICEDISCOUNTS" TO "BOUSR";
  GRANT REFERENCES ON "ANAPLAN"."OL_SALESINVOICEDISCOUNTS" TO "BOUSR";
  GRANT READ ON "ANAPLAN"."OL_SALESINVOICEDISCOUNTS" TO "BOUSR";
  GRANT ON COMMIT REFRESH ON "ANAPLAN"."OL_SALESINVOICEDISCOUNTS" TO "BOUSR";
  GRANT QUERY REWRITE ON "ANAPLAN"."OL_SALESINVOICEDISCOUNTS" TO "BOUSR";
  GRANT DEBUG ON "ANAPLAN"."OL_SALESINVOICEDISCOUNTS" TO "BOUSR";
  GRANT FLASHBACK ON "ANAPLAN"."OL_SALESINVOICEDISCOUNTS" TO "BOUSR";
  GRANT SELECT ON "ANAPLAN"."OL_SALESINVOICEDISCOUNTS" TO "LOTMAT";
  GRANT SELECT ON "ANAPLAN"."OL_SALESINVOICEDISCOUNTS" TO "KAPRIS";



--TD_MONDAYS


  CREATE TABLE "ANAPLAN"."TD_MONDAYS" 
   (	"COWEST" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


  GRANT SELECT ON "ANAPLAN"."TD_MONDAYS" TO "LOTMAT";
  GRANT ALTER ON "ANAPLAN"."TD_MONDAYS" TO "CESU";
  GRANT DELETE ON "ANAPLAN"."TD_MONDAYS" TO "CESU";
  GRANT INDEX ON "ANAPLAN"."TD_MONDAYS" TO "CESU";
  GRANT INSERT ON "ANAPLAN"."TD_MONDAYS" TO "CESU";
  GRANT SELECT ON "ANAPLAN"."TD_MONDAYS" TO "CESU" WITH GRANT OPTION;
  GRANT UPDATE ON "ANAPLAN"."TD_MONDAYS" TO "CESU";
  GRANT REFERENCES ON "ANAPLAN"."TD_MONDAYS" TO "CESU";
  GRANT READ ON "ANAPLAN"."TD_MONDAYS" TO "CESU";
  GRANT ON COMMIT REFRESH ON "ANAPLAN"."TD_MONDAYS" TO "CESU";
  GRANT QUERY REWRITE ON "ANAPLAN"."TD_MONDAYS" TO "CESU";
  GRANT DEBUG ON "ANAPLAN"."TD_MONDAYS" TO "CESU";
  GRANT FLASHBACK ON "ANAPLAN"."TD_MONDAYS" TO "CESU";
  GRANT ALTER ON "ANAPLAN"."TD_MONDAYS" TO PUBLIC;
  GRANT DELETE ON "ANAPLAN"."TD_MONDAYS" TO PUBLIC;
  GRANT INDEX ON "ANAPLAN"."TD_MONDAYS" TO PUBLIC;
  GRANT INSERT ON "ANAPLAN"."TD_MONDAYS" TO PUBLIC;
  GRANT SELECT ON "ANAPLAN"."TD_MONDAYS" TO PUBLIC;
  GRANT UPDATE ON "ANAPLAN"."TD_MONDAYS" TO PUBLIC;
  GRANT REFERENCES ON "ANAPLAN"."TD_MONDAYS" TO PUBLIC;
  GRANT READ ON "ANAPLAN"."TD_MONDAYS" TO PUBLIC;
  GRANT ON COMMIT REFRESH ON "ANAPLAN"."TD_MONDAYS" TO PUBLIC;
  GRANT QUERY REWRITE ON "ANAPLAN"."TD_MONDAYS" TO PUBLIC;
  GRANT DEBUG ON "ANAPLAN"."TD_MONDAYS" TO PUBLIC;
  GRANT FLASHBACK ON "ANAPLAN"."TD_MONDAYS" TO PUBLIC;
  GRANT SELECT ON "ANAPLAN"."TD_MONDAYS" TO "KAPRIS";



--TD_SALES_SUM

  CREATE TABLE "ANAPLAN"."TD_SALES_SUM" 
   (	"DIVISION" VARCHAR2(108 BYTE), 
	"PERIOD" VARCHAR2(108 BYTE), 
	"CUSTOMERCODE" VARCHAR2(108 BYTE), 
	"ITEMCODE" VARCHAR2(108 BYTE), 
	"VOLUME" NUMBER, 
	"GROSS" NUMBER, 
	"DISCOUNT" NUMBER, 
	"EXCISE" NUMBER, 
	"DEPOFEE" NUMBER, 
	"SALESBONUS" NUMBER, 
	"NETSALES" NUMBER, 
	"COGS" NUMBER, 
	"PROMODISCOUNT" NUMBER, 
	"EXT_M1" NUMBER, 
	"EXT_M2" NUMBER, 
	"EXT_M3" NUMBER, 
	"ATTR1" VARCHAR2(108 BYTE), 
	"ATTR2" VARCHAR2(108 BYTE), 
	"ATTR3" VARCHAR2(108 BYTE), 
	"DELIVERYCOST" NUMBER, 
	"CAMPAIGNVOLUME" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


  GRANT ALTER ON "ANAPLAN"."TD_SALES_SUM" TO "BOUSR";
  GRANT DELETE ON "ANAPLAN"."TD_SALES_SUM" TO "BOUSR";
  GRANT INDEX ON "ANAPLAN"."TD_SALES_SUM" TO "BOUSR";
  GRANT INSERT ON "ANAPLAN"."TD_SALES_SUM" TO "BOUSR";
  GRANT SELECT ON "ANAPLAN"."TD_SALES_SUM" TO "BOUSR";
  GRANT UPDATE ON "ANAPLAN"."TD_SALES_SUM" TO "BOUSR";
  GRANT REFERENCES ON "ANAPLAN"."TD_SALES_SUM" TO "BOUSR";
  GRANT READ ON "ANAPLAN"."TD_SALES_SUM" TO "BOUSR";
  GRANT ON COMMIT REFRESH ON "ANAPLAN"."TD_SALES_SUM" TO "BOUSR";
  GRANT QUERY REWRITE ON "ANAPLAN"."TD_SALES_SUM" TO "BOUSR";
  GRANT DEBUG ON "ANAPLAN"."TD_SALES_SUM" TO "BOUSR";
  GRANT FLASHBACK ON "ANAPLAN"."TD_SALES_SUM" TO "BOUSR";
  GRANT SELECT ON "ANAPLAN"."TD_SALES_SUM" TO "LOTMAT";
  GRANT SELECT ON "ANAPLAN"."TD_SALES_SUM" TO "KAPRIS";


--TD_SALES_SUM_DAILY

  CREATE TABLE "ANAPLAN"."TD_SALES_SUM_DAILY" 
   (	"DIVISION" VARCHAR2(108 BYTE), 
	"INVOICEDATE" VARCHAR2(108 BYTE), 
	"DELIVERYDATE" VARCHAR2(108 BYTE), 
	"CUSTOMERCODE" VARCHAR2(108 BYTE), 
	"ITEMCODE" VARCHAR2(108 BYTE), 
	"VOLUME" VARCHAR2(108 BYTE), 
	"ORDER_VOLUME" VARCHAR2(108 BYTE), 
	"CAMPAIGN" VARCHAR2(108 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE INDEX "ANAPLAN"."TD_SALES_SUM_DAILY_INDEX1" ON "ANAPLAN"."TD_SALES_SUM_DAILY" ("DIVISION", "DELIVERYDATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


  GRANT SELECT ON "ANAPLAN"."TD_SALES_SUM_DAILY" TO "LOTMAT";
  GRANT SELECT ON "ANAPLAN"."TD_SALES_SUM_DAILY" TO "KAPRIS";


--TD_SALES_SUM_DAILY_FULL

  CREATE TABLE "ANAPLAN"."TD_SALES_SUM_DAILY_FULL" 
   (	"DIVISION" VARCHAR2(108 BYTE), 
	"INVOICEDATE" VARCHAR2(108 BYTE), 
	"DELIVERYDATE" VARCHAR2(108 BYTE), 
	"CUSTOMERCODE" VARCHAR2(108 BYTE), 
	"ITEMCODE" VARCHAR2(108 BYTE), 
	"VOLUME" NUMBER, 
	"ORDER_VOLUME" NUMBER, 
	"ATTR1" VARCHAR2(108 BYTE), 
	"ATTR2" VARCHAR2(108 BYTE), 
	"ATTR3" VARCHAR2(108 BYTE), 
	"CAMPAIGN" VARCHAR2(108 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


  GRANT SELECT ON "ANAPLAN"."TD_SALES_SUM_DAILY_FULL" TO "LOTMAT";
  GRANT SELECT ON "ANAPLAN"."TD_SALES_SUM_DAILY_FULL" TO "KAPRIS";


--TD_SALES_SUM_FULL

  CREATE TABLE "ANAPLAN"."TD_SALES_SUM_FULL" 
   (	"DIVISION" VARCHAR2(108 BYTE), 
	"PERIOD" VARCHAR2(108 BYTE), 
	"CUSTOMERCODE" VARCHAR2(108 BYTE), 
	"ITEMCODE" VARCHAR2(108 BYTE), 
	"VOLUME" NUMBER, 
	"GROSS" NUMBER, 
	"DISCOUNT" NUMBER, 
	"EXCISE" NUMBER, 
	"DEPOFEE" NUMBER, 
	"SALESBONUS" NUMBER, 
	"NETSALES" NUMBER, 
	"COGS" NUMBER, 
	"PROMODISCOUNT" NUMBER, 
	"EXT_M1" NUMBER, 
	"EXT_M2" NUMBER, 
	"EXT_M3" NUMBER, 
	"ATTR1" VARCHAR2(108 BYTE), 
	"ATTR2" VARCHAR2(108 BYTE), 
	"ATTR3" VARCHAR2(108 BYTE), 
	"DELIVERYCOST" NUMBER, 
	"CAMPAIGNVOLUME" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


  GRANT SELECT ON "ANAPLAN"."TD_SALES_SUM_FULL" TO "BOUSR";
  GRANT SELECT ON "ANAPLAN"."TD_SALES_SUM_FULL" TO "LOTMAT";
  GRANT SELECT ON "ANAPLAN"."TD_SALES_SUM_FULL" TO "KAPRIS";
